server:
  port: 8080

spring:
  profiles:
    active: develop, test
  main:
    banner-mode: 'off'

---

spring:
  profiles: develop
  main:
    banner-mode: 'off'

---

spring:
 profiles: test
 main:
   banner-mode: 'off'


